# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NodeJS code to Lambda

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Find Lambda Function
        run: |
            # Specify the Lambda function name you want to locate
            lambda_function_name="lambda-nodejs-app"
  
            # Use the AWS CLI to describe the Lambda function
            aws lambda get-function --function-name "lambda-nodejs-app"
            
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws --version 

      - name: Run output.js and capture the output
        id: capture-output
        run: |
            # output=$(node output.js)
            # echo "::set-output name=OUTPUT::$output"
            echo "OUTPUT_VARIABLE=value" >> $GITHUB_ENV
            echo ${{ env.OUTPUT_VARIABLE }}
            
      - name: Publish to Lambda
        run: | # Use the captured output and publish it to Lambda
            aws lambda update-function-code --function-name $lambda_function_name \
            --zip-file fileb://<(echo "$OUTPUT_VARIABLE")


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm list
      - run: ls -la
      - run: node output.js

        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.npm_token}}
